name: hop
version: 0.21.0-dev
author: Kevin Moore <kevin@thinkpixellab.com>
description: Dart Task Framework
homepage: https://github.com/kevmoo/hop.dart
documentation: http://kevmoo.github.io/hop.dart
environment:
  sdk: '>=0.4.7+1'
dependencies:
  unittest: '>=0.4.7+1'
  bot: '>=0.20.0-dev'
  args: '>=0.4.7+1'
  bot_io: '>=0.20.0-dev'
  logging: '>=0.4.7+1'
  pathos: '>=0.4.7+1'
  meta: '>=0.4.7+1'
dev_dependencies:
  html5lib: '>=0.4.3'
