name: hop
version: 0.32.1-dev
author: Hop Project Authors <hop_authors@j832.com>
description: Dart Task Framework
homepage: https://github.com/kevmoo/hop
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  args: '>=0.9.0 <0.14.0'
  bot: '>=0.26.0 <0.29.0'
  bot_io: ^0.26.1
  collection: ^1.0.0
  completion: ^0.1.4
  logging: '>=0.9.1 <0.13.0'
  path: ^1.0.0
dev_dependencies:
  test: any
executables:
  bench:
